### ISSUE TITLE
store.watch

### ISSUE THREAD

**Issue by cloook** [Coffcer/vue-chat#14]
store.watch(
    (state) => state.sessions,
    (val) => {
        console.log('CHANGE: ', val);
        localStorage.setItem('vue-chat-session', JSON.stringify(val));
    },
    {
        deep: true
    }
);
这里的(val)=>指的是什么呢

**Comment by Coffcer** [comment]
这是ES6写法，指代function(val){}

**Comment by HiKWang** [comment]
`val`指的是`state.sessions`.
`store.watch`是用来监听第一个函数的返回值的，第二个函数接受的参数`val`就是第一个参数的返回值`state.sessins`.
