### ISSUE TITLE
在search 搜索框里输入条件以后, 点击过滤后的头像没有跳转至对应的对话框(Session没有对应)

### ISSUE THREAD

**Issue by jinxuanw-clairvoyant** [Coffcer/vue-chat#3]
参见:![gif](http://g.recordit.co/0gThqZp8tt.gif)

当我搜webpack时, 虽然过滤了`示例介绍`的头像, 但是对应的对话框(session)却没有改变

因为在list component 里的select method中, 使用了v-for的$index变量. 但是该变量在使用了过滤器以后导致$index变量发生了变化.  比如在上图的例子中.  示例介绍一开始的$index 是 0 而 webpack的$index是1. 但是在使用了filter以后. webpack 的$index变成0了, 所以对应的对话框(active session) 没有发生变化.

**Comment by Coffcer** [comment]
thanks，已修复
