### ISSUE TITLE
有段代码不是很明白

### ISSUE THREAD

**Issue by cocody** [Coffcer/vue-chat#6]
`if (e.ctrlKey && e.keyCode === 13 && this.text.length) {
  this.session.messages.push({
                        text: this.text,
                        date: new Date(),
                        self: true
                    });
                    this.text = '';
                }`

这里this.session.messages.push(); 只不过push到这个模块的session.messages里去，并没有dispatch到父组件去，那么父组件是怎样检测到.session.的变化从而改变视图呢？

> 类似于用 v-bind 绑定 HTML 特性到一个表达式，也可以用 v-bind 绑定动态 Props 到父组件的数据。每当父组件的数据变化时，也会传导给子组件

这里并没有说子组件可以传递给父组件

**Comment by vboar** [comment]
"注意如果 prop 是一个对象或数组，是按引用传递。在子组件内修改它会影响父组件的状态，不管是使用哪种绑定类型。"

**Comment by cocody** [comment]
god！没看到这段！感谢
