### ISSUE TITLE
与xmpp服务器连接不上

### ISSUE THREAD

**Issue by kevinlelelily** [Coffcer/vue-chat#8]
不知博主对于这个框架有没有运用strophe连接xmpp的实例？我整合过来的话xmpp连接不上

**Comment by Coffcer** [comment]
没有尝试过，但这只是个前端DEMO，不是个框架，理论上和你要用什么通讯协议没关系

**Comment by kevinlelelily** [comment]
@Coffcer OK，解决了

**Comment by iceyu07** [comment]
@kevinlelelily 可以分享一下怎么在vue内集成strophe吗？
